# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40658d6c943f09d7e506f639d602ba3997dd6ebd53f3efedc4f9baf71bd29bb29cb22e55b200a8333c892b8485296e192fbd67fc508d6bffb33a25edca14ad68

test:
  secret_key_base: f3e7b4f53bab21921fd5becb88b6ac5e98e8d35d089eddae252c9bd504e2bfe0dc0d4270399ff60afbd1e989e382535ef28f5233f27060fbf9614edf96a469b1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
